# Generated by Django 5.2.4 on 2025-10-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="checkout_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
