[build]
builder = "dockerfile"

[services.web]
dockerfilePath = "./Dockerfile"
startCommand = "python Backend/Portafy/manage.py migrate --noinput && python Backend/Portafy/manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --worker-class sync --max-requests 100 --max-requests-jitter 10 --keep-alive 5 --log-level info"
healthcheckPath = "/admin/"
healthcheckTimeout = 100
autoDeploy = false

[services.worker]
dockerfilePath = "./Dockerfile.worker"
startCommand = "celery -A Backend.Portafy.config worker --loglevel=info --concurrency=1 --max-tasks-per-child=50"

[services.db]
# PostgreSQL service - Railway will auto-provision from docker-compose.yml

[services.redis]
# Redis service - Railway will auto-provision from docker-compose.yml
