name: Placeholder CI

on:
    workflow_dispatch:

jobs:
    noop:
        runs-on: ubuntu-latest
        steps:
            - name: Do nothing
              run: echo "This is a placeholder workflow."
